api:
  dashboard: true

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock
    network: devsec-keycloak-network
  file:
    filename: etc/traefik/config.yml

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  tlsresolver:
    acme:
      email: development@mfuchs.dev
      storage: /etc/traefik/letsencrypt/acme.json
      httpchallenge:
        entryPoint: web