name: Publish images

on:
  push:
    branches:
      - main

jobs:
  publish-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Log into registry
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name:  Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle bootBuildImage
        working-directory: backend
        run: gradle bootBuildImage  --imageName="ghcr.io/theexiile1305/devsec-keycloak-backend:${GITHUB_SHA::7}"
        env:
          CI_REGISTRY_USER: ${{ github.actor }}
          CI_REGISTRY_PASSWORD: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  publish-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        working-directory: frontend
        run: docker build -t ghcr.io/theexiile1305/devsec-keycloak-frontend:${GITHUB_SHA::7} .

      - name: Push image
        run: docker push ghcr.io/theexiile1305/devsec-keycloak-frontend:${GITHUB_SHA::7}

  publish-keycloak:
    runs-on: ubuntu-latest

    steps:
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle jar
        run: gradle jar
        working-directory: keycloak

      - name: Build image
        run: docker build -t ghcr.io/theexiile1305/devsec-keycloak-keycloak:${GITHUB_SHA::7} .
        working-directory: keycloak

      - name: Push image
        run: docker push ghcr.io/theexiile1305/devsec-keycloak-keycloak:${GITHUB_SHA::7}